### ISSUE TITLE
Error on linux_SS angles  (calculate_step_sizes_and_angles())

### ISSUE THREAD

**Issue by sameerbau** [liamholtlab/GEMspa#4]
```
Traj_XYT091.csv_crop.csv 
SS/Angles number of tracks: 392
Traceback (most recent call last):
  File "/home/LAB/Desktop/GEMspa/main_gui.py", line 587, in on_go
    traj_an.calculate_step_sizes_and_angles()
  File "/home/Lab/Desktop/GEMspa/trajectory_analysis.py", line 1862, in calculate_step_sizes_and_angles
    cur_tlag_data = cur_tlag_data[np.logical_not(np.isnan(cur_tlag_data))]
TypeError: ufunc 'isnan' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''

```

hello!

Getting this error  when running this file: https://drive.google.com/drive/folders/1QR9ezX3PIXFxk7EHhNiNvKJnb_VucM8o?usp=sharing

Basically the diffusion values run well but the angles stuff crashes. The output folder shows only the 3 diffusion plots.
Any advice?

Sameer

**Comment by snkeegan** [comment]
I wasn't able to re-create this error from the file you sent, but I have added a check that I'm hoping will fix it.  Please download the latest code from the main branch.

**Comment by sameerbau** [comment]
Works! Thank you!
