### ISSUE TITLE
Request to change Image names in sample data to be DNA_

### ISSUE THREAD

**Issue by sameerbau** [liamholtlab/GEMspa#5]
In the current version, the sample files (for overlaying ROIs and Trajectories) are named as: BG_DMSO_AxonLeft_2h_012

while in the gui, the prefix used by default is DNA_.

Of course one can change it to BG_, but not knowing this can cause some time and trouble. Gentle suggestion to name the sample files as DNA_ or vice versa.

Thanks!

**Comment by snkeegan** [comment]
Yes, thanks for that suggestion!  I have changed the file names.
